"""Checkins

Revision ID: 2da4602ae513
Revises: 598174bcc863
Create Date: 2021-11-26 07:02:01.455406

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '2da4602ae513'
down_revision = '598174bcc863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('nakamal_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['nakamal_id'], ['nakamal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    # ### end Alembic commands ###
