"""aliases not null

Revision ID: 82571c45f3b9
Revises: bd7d3bb2bd1b
Create Date: 2022-01-19 22:20:21.135823

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82571c45f3b9'
down_revision = 'bd7d3bb2bd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Update nakamal undefined light value
    res = conn.execute("SELECT id FROM nakamal WHERE aliases IS NULL")
    results = res.fetchall()
    for res in results:
        print(res)
        conn.execute(f"UPDATE nakamal SET aliases = array[]::text[] WHERE id = '{str(res[0])}'")
    op.alter_column('nakamal', 'aliases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nakamal', 'aliases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###
