"""Checkins

Revision ID: a5e31062a922
Revises: 598174bcc863
Create Date: 2021-11-23 09:13:14.196870

"""
from alembic import op
import ormar
import sqlalchemy as sa
import fastapi_users
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5e31062a922'
down_revision = '598174bcc863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('nakamal_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['nakamal_id'], ['nakamal.id'], name='fk_checkin_nakamal_id_nakamal'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_checkin_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    # ### end Alembic commands ###
