"""NakamalKavaSource

Revision ID: 02d698935816
Revises: 2eb26ab7c122
Create Date: 2022-01-02 10:19:28.947041

"""
import uuid
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '02d698935816'
down_revision = '2eb26ab7c122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nakamal_kava_source',
    sa.Column('id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('island', sa.String(), nullable=True),
    sa.Column('province', sa.Enum('UNDEFINED', 'ANY', 'TORBA', 'PENAMA', 'SANMA', 'MALAMPA', 'SHEFA', 'TAFEA', name='province'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Add initial row to nakamal_kava_area that handles undefined kava source / initial default value since database has nakamals already
    nakamal_kava_source_id = uuid.uuid4()
    op.execute(f"INSERT INTO nakamal_kava_source(id, province) VALUES('{str(nakamal_kava_source_id)}', 'UNDEFINED')")
    # Add "ANY" kava source
    op.execute(f"INSERT INTO nakamal_kava_source(id, province) VALUES('{str(uuid.uuid4())}', 'ANY')")

    # Add column with default value set temporarily
    op.add_column('nakamal', sa.Column('kava_source_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False, server_default=str(nakamal_kava_source_id)))
    # Remove column default value
    op.alter_column('nakamal', 'kava_source_id', server_default=None)
    
    op.create_foreign_key(None, 'nakamal', 'nakamal_kava_source', ['kava_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nakamal', type_='foreignkey')
    op.drop_column('nakamal', 'kava_source_id')
    op.drop_table('nakamal_kava_source')
    # ### end Alembic commands ###
