"""Images

Revision ID: 598174bcc863
Revises: c17e4fa05388
Create Date: 2021-10-24 17:31:40.331293

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '598174bcc863'
down_revision = 'c17e4fa05388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filetype', sa.String(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.Column('nakamal_id', fastapi_users_db_sqlalchemy.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['nakamal_id'], ['nakamal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
