"""chief_id added to Nakamal

Revision ID: 919342d262c5
Revises: 804a19852b52
Create Date: 2022-06-02 17:14:07.125112

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '919342d262c5'
down_revision = '804a19852b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nakamal', sa.Column('chief_id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=True))
    op.create_foreign_key(None, 'nakamal', 'user', ['chief_id'], ['id'])
    op.add_column('nakamal_version', sa.Column('chief_id', fastapi_users_db_sqlalchemy.guid.GUID(), autoincrement=False, nullable=True))
    op.add_column('nakamal_version', sa.Column('chief_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nakamal_version', 'chief_id_mod')
    op.drop_column('nakamal_version', 'chief_id')
    op.drop_constraint(None, 'nakamal', type_='foreignkey')
    op.drop_column('nakamal', 'chief_id')
    # ### end Alembic commands ###
