"""Add TimeMixin to Nakamal

Revision ID: bc998ca58ebc
Revises: 82571c45f3b9
Create Date: 2022-02-25 16:01:52.803571

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'bc998ca58ebc'
down_revision = '82571c45f3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nakamal', sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    op.add_column('nakamal', sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))

    # Update nakamal created_at
    conn = op.get_bind()
    res = conn.execute("SELECT id FROM nakamal WHERE created_at IS NULL")
    results = res.fetchall()
    for res in results:
        conn.execute(f"UPDATE nakamal SET created_at = now() WHERE id = '{str(res[0])}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nakamal', 'updated_at')
    op.drop_column('nakamal', 'created_at')
    # ### end Alembic commands ###
